name: "Validate BPMN process models"
description: "GitHub Action workflow for automated validation of BPMN process models"
author: "Kristoffer Högberg"

inputs:
  bpmn-files-path:
    description: 'Location of your process models.'
    required: true
  custom-rules-folder:
    description: 'Location of your custom bpmnlint rules.'
    required: true
  bpmnlintrc-path:
    description: "Location of your bpmnlintrc configuration file."
    required: true

runs:
  using: "composite"
  steps:
    # Set up NodeJs
    - name: Set up NodeJs
      uses: actions/setup-node@v2
      with:
        node-version: 16.20.1

    # Install bpmnlint
    - name: Install bpmnlint
      shell: bash
      run: npm install -g bpmnlint

    # Run action scriptSchema validation
    - run: node ${{ github.workspace }}/dist/index.js
      shell: bash

branding:
  icon: 'activity'
  color: 'green'
