name: "Validate BPMN process models"

on:
  workflow_call:
    inputs:
      bpmn-files-path:
        description: 'Location of your process models.'
        required: true
        type: string
      custom-rules-folder:
        description: 'Location of your custom bpmnlint rules.'
        required: true
        type: string
      bpmnlintrc-path:
        description: "Location of your bpmnlintrc configuration file."
        required: true
        type: string
jobs:
  validate_bpmn_process_models:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up NodeJs
      - name: Set up NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.1

      # Install bpmnlint
      - name: Install bpmnlint
        run: npm install -g bpmnlint

      - uses: ./
        with:
          bpmn-files-path: ${{ inputs.bpmn-files-path }}
          custom-rules-folder: ${{ inputs.custom-rules-folder }}
          bpmnlintrc-path:  ${{ inputs.bpmnlintrc-path }}

