name: "Test TS Action"

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          bpmn-files-path: "<path-to-bpmn-files>"
          custom-rules-folder: "<path-to-custom-rules-folder>"
          bpmnlintrc-path: "<path-to-bpmnlintrc-config"
