name: "Validate BPMN process models"

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up NodeJs
      - name: Set up NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.1

      # Install bpmnlint
      - name: Install bpmnlint
        run: npm install -g bpmnlint

      - uses: ./
        with:
          bpmn-files-path:  BPMN
          custom-rules-folder: custom_rules
          bpmnlintrc-path: BPMN/.bpmnlintrc

      # Run BPMN validation and output result
      - name: Run BPMN validation and output result
        run: |
          for file in ${{ inputs.bpmn-files-path }}/*.bpmn; do
            if [ -z "$(bpmnlint "$file")" ]; then
              echo -e "\033[32mNo errors found in $file\033[0m"
            else
              echo -e "\033[31mErrors found in $file:\033[0m"
              bpmnlint "$file" || true
            fi
          done
