name: "Test TS Action"

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          bpmn-files-path: "BPMN/"
          custom-rules-folder: "<path-to-custom-rules-folder>"
          bpmnlintrc-path: "<path-to-bpmnlintrc-config"
          
      - name: Search for rules folder
        run: find / -type d -name "rules" 2>/dev/null
