name: BPMN-Lint Validation

on:
  workflow_call:
    inputs:
      bpmn-file-path:
        required: true
        type: string
      custom-rules-folder:
        required: true
        type: string
      bpmnlintrc-path: 
        required: true
        type: string

jobs:
  validate_bpmn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0

      - name: Install npm packages
        run: npm install -g bpmnlint
      
      - name: Read BPMN file content
        run: |
          cat "${{ inputs.bpmn-file-path }}" > bpmn-file-content.txt
          
      - name: Output BPMN file content
        run: cat bpmn-file-content.txt
        
      - name: Copy custom rules to bpmnlint
        run: cp -r ${{ inputs.custom-rules-folder }}/ /opt/hostedtoolcache/node/18.17.0/x64/lib/node_modules/bpmnlint/rules/
        
      - name: Copy .bpmnlintrc to BPMN folder
        run: cp "${{ inputs.bpmnlintrc-path }}" "${{ github.workspace }}/"
        
      - name: Run BPMNLint
        run: bpmnlint bpmn-file-content.txt
