name: BPMN-Lint Validation

on:
  workflow_call:
    inputs:
      bpmn-file-path:
        required: true
        type: string
      custom-rules-folder:
        required: true
        type: string
      bpmnlintrc-path: 
        required: true
        type: string
        
defaults:
  run:
    working-directory:
      validate-bpmn

jobs:
  validate_bpmn:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 18x]

    steps:
      - name: Install npm packages
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g bpmnlint

      - name: View contents of root directory
        run: ls -al /

      - name: Read BPMN file content
        run: |
          cat "${{ inputs.bpmn-file-path }}" > bpmn-file-content.bpmn

      - name: Output BPMN file content
        run: cat bpmn-file-content.bpmn

      - name: Create .bpmnlintrc
        run: |
          echo '{
              "extends": "bpmnlint:recommended",
              "rules": {
                  "force-digit-id": "error",
                  "force-service-task-type": "error"
              }
          }
          ' > .bpmnlintrc

      - name: Output .bpmnlintrc content
        run: cat .bpmnlintrc

      - name: Copy custom rules to bpmnlint
        run: cp -r ${{ inputs.custom-rules-folder }} ${{ github.workspace }}/bpmnlint/rules/

      - name: Run BPMNLint (ignore exit code 1)
        run: bpmnlint bpmn-file-content.bpmn || true
