name: "Validate BPMN process models"

on:
  workflow_dispatch:

jobs:
  validate_bpmn _process_models:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up NodeJs
      - name: Set up NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.1

      # Install bpmnlint
      - name: Install bpmnlint
        run: npm install -g bpmnlint

      - uses: ./
        with:
          bpmn-files-path:  BPMN
          custom-rules-folder: custom_rules
          bpmnlintrc-path: BPMN/.bpmnlintrc

