name: "Validate BPMN process models"

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: ./
        with:
          bpmn-files-path: "BPMN"
          custom-rules-folder: "custom_rules"
          bpmnlintrc-path: "BPMN"

