name: BPMN-Lint Validation

on:
  workflow_call:
    inputs:
      bpmn-file-path:
        required: true
        type: string
      custom-rules-folder:
        required: true
        type: string
      bpmnlintrc-path: 
        required: true
        type: string

jobs:
  validate_bpmn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.0

      - name: Install bpmnlint
        run: npm install -g bpmnlint
        
        
      - name: Install jq
        run: sudo apt-get install jq

      - name: Search for bpmnlint directory
        run: |
          # Search for the bpmnlint directory using the find command
          # and save the result in a variable
          bpmnlint_dir=$(find / -type d -name "bpmnlint" 2>/dev/null)

          # Output the bpmnlint directory path
          echo "BPMNLint Directory: $bpmnlint_dir"

          # Store the bpmnlint directory path as an output variable
          echo "BPMNLINT_DIRECTORY=$bpmnlint_dir" >> $GITHUB_ENV

      - name: Use bpmnlint directory path
        run: |
          # Use the stored bpmnlint directory path
          echo "Using BPMNLint Directory: $BPMNLINT_DIRECTORY"   

      - name: View contents of root directory
        run: ls -la /
        
      - name: Search for bpmnlint directory
        id: search_bpmnlint
        run: |
          bpmnlint_dir=$(find / -type d -name "bpmnlint" 2>/dev/null)

          echo "BPMNLint Directory: $bpmnlint_dir"

          echo "BPMNLINT_DIRECTORY=$bpmnlint_dir" >> $GITHUB_ENV   
        
      - name: Read BPMN file content
        run: |
          cat "${{ inputs.bpmn-file-path }}" > bpmn-file-content.bpmn

      - name: Output BPMN file content
        run: cat bpmn-file-content.bpmn

      - name: Create .bpmnlintrc
        run: |
          echo '{
              "extends": "bpmnlint:recommended",
              "rules": {
                  "force-digit-id": "error",
                  "force-service-task-type": "error"
              }
          }
          ' > .bpmnlintrc

      - name: Output .bpmnlintrc content
        run: cat .bpmnlintrc

      - name: Copy custom rules to bpmnlint/rules
        run: cp -r ${{ inputs.custom-rules-folder }} ${{ github.workspace }}/bpmnlint/rules/

      - name: Run BPMNLint (ignore exit code 1)
        run: bpmnlint bpmn-file-content.bpmn || true
